### ISSUE TITLE
current status?

### ISSUE THREAD

**Issue by KeLaiFu** [versusentropy/wavefolder#1]
I was searching for a wavefolder and found this one, which looks very interesting but theres no status on the current situation of the module. Is it safe to order the PCBs?

Thanks for your contributions to SDIY so far, some very interesting stuff on the repo.

**Comment by versusentropy** [comment]
Hi @KeLaiFu,
it works fine. The attenuverters for the CV are reversed. That could be fixed easily (or doesn't matter much). The whole thing is a bit noisy, but I like it. Especially the saturator.
check Colin Bender's discord #diy https://discord.gg/NK2qdwFb
I still have 2 PCBs (Schräg, seqswt, halbmix and clockdivider as well), that I would share for production+shipping costs.
